---
- name: Deleting welcome page
  file:
    state: absent
    path: "/etc/apache2/sites-enabled/000-default.conf"
  notify: apache reload

- name: Creating the configuration file for '{{ item.value.serverName }}'
  template: src=templates/vhost.j2 dest=/etc/apache2/sites-available/{{ item.value.serverName }}.conf
  notify: apache reload

- name: Configuring ports for '{{ item.value.serverName }}'
  lineinfile:
    path: /etc/apache2/ports.conf
    line: 'Listen {{ item.value.http_port }}'
  notify: apache reload

- name: Disabling ports
  lineinfile:
    path: /etc/apache2/ports.conf
    state: absent
    line: 'Listen {{ port }}'
  with_items: "{{ http_port_disabled }}"
  loop_control:
    loop_var: port
  when: http_port_disabled is defined
  notify: apache reload

- name: Enabling modules..."{{ enable_mods }}"
  file:
    src: /etc/apache2/mods-available/{{ mods }}
    dest: /etc/apache2/mods-enabled/{{ mods }}
    state: link
  with_items: "{{ mods_enabled }}"
  loop_control:
    loop_var: mods
  when: mods_enabled is defined
  notify: apache reload

- name: Enabling '{{ item.value.serverName }}'
  file:
    src: /etc/apache2/sites-available/{{ item.value.serverName }}.conf
    dest: /etc/apache2/sites-enabled/{{ item.value.serverName }}.conf
    owner: www-data
    group: www-data
    state: link
  notify: apache reload

