---
- name: Deleting welcome page
  file:
    state: absent
    path: "/etc/httpd/conf.d/welcome.conf"

- name: Creating the configuration file for {{ item.value.serverName }}
  template: src=templates/vhost.j2 dest=/etc/httpd/conf.d/{{ item.value.serverName }}.conf
  notify: httpd reload

- name: Configuring ports for '{{ item.value.serverName }}'
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: 'Listen {{ item.value.http_port }}'
  notify: httpd reload

- name: Disabling ports
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    state: absent
    line: 'Listen {{ port }}'
  with_items: "{{ http_port_disabled }}"
  loop_control:
    loop_var: port
  when: http_port_disabled is defined
  notify: httpd reload