---

- name: Include variables for RedHat systems
  include_vars: vars-RedHat.yml

- name: Deleting welcome page
  file:
    state: absent
    path: "{{ server_conf }}/conf.d/welcome.conf"

- name: Delete default Document Root
  replace:
    path: "{{ server_conf }}/conf/httpd.conf"
    regexp: 'DocumentRoot "/var/www/html"'
    replace: 'DocumentRoot "/var/www/"'

- name: Creating the configuration file for {{ item.value.serverName }}
  template: src=templates/vhost.j2 dest="{{ server_conf }}/conf.d/{{ item.value.serverName }}.conf"
  notify: httpd reload

- name: Configuring ports for '{{ item.value.serverName }}'
  lineinfile:
    path: "{{ server_conf }}/conf/httpd.conf"
    line: 'Listen {{ item.value.http_port }}'
  notify: httpd reload

- name: Disabling ports
  lineinfile:
    path: "{{ server_conf }}/conf/httpd.conf"
    state: absent
    line: 'Listen {{ port }}'
  with_items: "{{ http_port_disabled }}"
  loop_control:
    loop_var: port
  when: http_port_disabled is defined
  notify: httpd reload

- name: Enabling modules...
  lineinfile:
    path: "{{ server_conf }}/conf.modules.d/00-base.conf"
    line: 'LoadModule {{ mods }}'
  with_items: "{{ httpd_modules }}"
  loop_control:
    loop_var: mods
  when: httpd_modules is defined
  notify: httpd reload

- name: Deploying '{{ item.value.serverName }}'
  git:
    repo: '{{ item.value.app_repo }}'
    dest: "{{ item.value.docRoot }}/{{ item.value.serverName }}"
    version: "{{ item.value.repo_version | default('master') }}"
    force: yes
  notify: httpd reload