---

- name: Deleting default configuration
  file:
    state: absent
    path: "{{ paths }}"
  with_items:
    - "{{ server_conf }}/sites-enabled/000-default.conf"
    - "{{ server_conf }}/sites-available/000-default.conf"
  loop_control:
    loop_var: paths
  notify: apache reload

- name: Creating the configuration file for '{{ item.value.serverName }}'
  template: src=templates/vhost.j2 dest="{{ server_conf }}/sites-available/{{ item.value.serverName }}.conf"
  when: item.value.vhost_state != 'absent'
  notify: apache reload

- name: Configuring ports for '{{ item.value.serverName }}'
  lineinfile:
    path: "{{ server_conf }}/ports.conf"
    line: 'Listen {{ item.value.http_port }}'
  notify: apache reload

- name: Disabling ports
  lineinfile:
    path: "{{ server_conf }}/ports.conf"
    state: absent
    line: 'Listen {{ port }}'
  with_items: "{{ http_port_disabled }}"
  loop_control:
    loop_var: port
  when: http_port_disabled is defined
  notify: apache reload

- name: Enabling modules...
  file:
    src: "{{ server_conf }}/mods-available/{{ mods }}"
    dest: "{{ server_conf }}/mods-enabled/{{ mods }}"
    state: link
  with_items: "{{ mods_enabled }}"
  loop_control:
    loop_var: mods
  when: mods_enabled is defined
  notify: apache reload

- name: Enabling '{{ item.value.serverName }}'
  file:
    src: "{{ server_conf }}/sites-available/{{ item.value.serverName }}.conf"
    dest: "{{ server_conf }}/sites-enabled/{{ item.value.serverName }}.conf"
    owner: www-data
    group: www-data
    state: link
  notify: apache reload

- name: Deploying '{{ item.value.serverName }}'
  git:
    repo: '{{ item.value.app_repo }}'
    dest: "{{ item.value.docRoot }}/{{ item.value.serverName }}"
    version: "{{ item.value.repo_version | default('master') }}"
    force: yes
  notify: apache reload